name: Build & Publish Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5 # Automatically reading .ruby-version doesn't seem to work
        bundler-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Set up minifier
      run: |
        sudo apt-get update
        sudo apt-get install minify

    - name: Set up libvips
      run: |
        sudo apt-get update
        sudo apt-get install libvips

    - name: Install shot-scraper
      run: |
        pip install shot-scraper
        shot-scraper install

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Build site
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production

    - name: Minify built files
      working-directory: ./_site
      run: |
        minify -r . -o .
        minify --type=json site.webmanifest -o .

    - name: Start Jekyll server for taking screenshot
      run: |
        bundle exec jekyll serve --skip-initial-build --no-watch --detach --port=4000
        
    - name: Take screenshot
      run: |
        shot-scraper "http://localhost:4000/${{ steps.pages.outputs.base_path }}/" -o "./_site/assets/images/homepage.png" --width 1280 --height 720

    - name: Stop Jekyll server for taking screenshot
      run: |
        pkill -f jekyll

    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3

  publish:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Publish site
      id: deployment
      uses: actions/deploy-pages@v4
