name: Build & Publish Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Set up minifier
      run: |
        sudo apt-get update
        sudo apt-get install minify

    - name: Set up libvips
      run: |
        sudo apt-get update
        sudo apt-get install libvips

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2

    - name: Build site
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production

    - name: Minify built files
      working-directory: ./_site
      run: |
        minify -r . -o .
        minify --type=json site.webmanifest -o .

    - name: Start Jekyll server for taking screenshot
      run: |
        bundle exec jekyll serve --skip-initial-build --no-watch --detach --port=4000

    - name: Take screenshot
      id: screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: http://localhost:4000/${{ steps.pages.outputs.base_path }}/
        destination: screenshot.png
        width: 1280
        height: 720
        is-java-script-enabled: false
        scale-factor: 1

    - name: Stop Jekyll server for taking screenshot
      run: |
        pkill -f jekyll

    - name: Move screenshot to output folder
      run: |
        mkdir -p ./_site/assets/images/
        mv ${{ steps.screenshot.outputs.path }} ./_site/assets/images/homepage.png

    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v1

  publish:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Publish site
      id: deployment
      uses: actions/deploy-pages@v1
